version: '3.3'

volumes:
  cassandra: {}
  nginx_tls: {}

services:
  cassandra:
    image: cassandra:2.1
    volumes:
     - cassandra:/var/lib/cassandra

  pithos:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    depends_on:
      - cassandra

  nginx-proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - nginx_tls:/etc/nginx/external/
    depends_on:
      - pithos
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
